name: setup-maestro-action
description: GitHub Actions setup CLI template
author: remarkablemark
inputs:
  version:
    description: CLI version
    required: false
    default: 2.0.3
runs:
  using: node24
  main: dist/index.js
branding:
  icon: phone
  color: gray-dark
